version: "3"
services:
  postgres:
    image: library/postgres:16-alpine
    environment:
      - POSTGRES_USER=program
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U program"]
      interval: 2s
      timeout: 2s
      retries: 1

  gateway_service:
    image: gateway_service
    build: ./services/gateway_service
    ports:
      - "8080:8080"
    networks:
      - default
  
  loyalty_service:
    image: loyalty_service
    build: ./services/loyalty_service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8050:8050"
    networks:
      - default
  
  #payment_service:
  
  #reservation_service:

volumes:
  db-data:
  
networks:
  default: